### ISSUE TITLE
Question: can I load models from any arbitrary URL, e.g. from S3?

### ISSUE THREAD

**Issue by nicodv** [microsoft/onnxjs#163]
I don't see any explicit documentation / examples discussing the use case of loading models from an external source such as S3.

Could I call `session.loadModel(https://s3.amazonaws.com/mybucket/mymodel.onnx)` and expect things to work?

**Comment by fs-eire** [comment]
if you are calling the `loadModel()` function in browser, it is actually using the [fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) to get the ONNX model specified by the URL passed in. Fetch API uses [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) so that make sure it is configured correctly.

links -
https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
https://docs.aws.amazon.com/AmazonS3/latest/dev/cors.html

**Comment by nicodv** [comment]
Thanks, that helps.
